[package]
name              = "zk-games-types"
version           = "0.1.0"
authors.workspace = true
edition.workspace = true
publish           = false

[dependencies]
serde          = { workspace = true }
sp1-primitives = { workspace = true }
