[package]
name              = "zk-games"
version           = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
sha2       = { workspace = true }
serde      = { version = "1.0", features = ["derive"] }
